name: Build and deploy PHP app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pgsql, pdo_pgsql

    - name: Print PHP info
      run: |
        php -v
        php -m | grep pgsql

    - name: Upload files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'finaxis-sergiodtaz'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
